name: pokedex
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^2.1.0
  cached_network_image: ^3.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_staggered_animations: ^1.0.0
  get: ^4.1.4
  md2_tab_indicator: ^1.0.2
  simple_animations: ^1.3.6
  sliding_sheet: ^0.5.0

flutter_icons:
  image_path: 'assets/icon/icon.png'  
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/pokeball.png
    - assets/images/pokeball_dark.png
    - assets/images/egg.png
    - assets/gifs/gif_poke.gif
  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
